### ISSUE TITLE
TODO -- excerpt from README

### ISSUE THREAD

**Issue by ivankovnatsky** [ivankovnatsky/articast#16]
- [ ] Fix issue when elevenlabs api key is not exposed to publish workflow:

```log
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_main.py::test_process_article_elevenlabs - elevenlabs.core.api_error.ApiError: status_code: 401, body: {'detail': {'status': 'invalid_api_key', 'message': 'Invalid API key'}}
=================== 1 failed, 5 passed, 1 warning in 24.14s ====================
Error: Process completed with exit code 1.
```

- [ ] Bypass Cloudflare block
- [ ] Minimize costs on tests
- [ ] Add ability to render images to text and send over to text to speech as well
- [ ] Shorten filename created
- [ ] Shorten article title printed to console
- [ ] Send to device right away
- [ ] Replace print with logger
- [ ] Remove redundant warnings in pytest
- [ ] Make sure pytest shows quota errors

**Comment by DomoMKT** [comment]
you can find what you're looking for at [www.nemesyslabs.com](https://www.nemesyslabs.com) and get high-quality text-to-speech conversions with extremely low latency.
